# 工作流的名称，会显示在GitHub的Actions页面上
name: Deploy Frontend to Server

# 触发工作流的条件
on:
  # 当有代码推送到 main 分支时
  push:
    branches:
      - main
    # 并且，只有当 frontend 目录或其子目录下的文件发生变动时才触发
    paths:
      - 'frontend/**'

# 定义工作流中要执行的任务
jobs:
  # 定义一个名为 build-and-deploy 的任务
  build-and-deploy:
    # 指定运行此任务的虚拟机环境，我们使用最新的Ubuntu系统
    runs-on: ubuntu-latest

    # 定义这个任务中要执行的一系列步骤
    steps:
      # 第一步：检出代码
      # 作用：将你的仓库代码完整地下载到GitHub提供的临时虚拟机中
      - name: Checkout Code
        uses: actions/checkout@v4

      # 第二步：设置 Node.js 环境
      # 作用：在虚拟机里安装指定版本的Node.js，为构建前端项目做准备
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/realtime-monitor-fronted/package-lock.json

      - name: Install Dependencies and Build
        run: |
          cd frontend/realtime-monitor-fronted
          npm install
          npm run build

      - name: Deploy to Server via rsync
        uses: Burnett01/rsync-deployments@v7.0.0
        with:
          switches: -avzr --delete
          path: frontend/realtime-monitor-fronted/dist/
          # 下面使用了我们之前在GitHub Secrets中设置好的变量，安全地进行连接
          remote_path: ${{ secrets.TARGET_DIR }}
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}